Terrain + skybox
tnicolas42/bomberman pull request #159
Opened 2020-04-22 18:50 UTC by zer0nim

Ajout d'un terrain sous le plateau de jeu et maj de la skybox
Je suis pas super satisfait de la nouvelle skybox mais j'arrive pas a faire mieux.
close #149 
close #118

2020-04-22 19:17 UTC, timnicolas approved these changes

2020-04-22 19:41 UTC, ebaudet requested changes
trop de proc pour le terrain

2020-04-23 17:39 UTC, tnicolas42 commented
le compteur de fps marche bien mais je suis a 16-17 fps... c'est pas assez

2020-04-24 08:15 UTC, zer0nim commented
@tnicolas42 oui j'ai encore rien changé, c'etait justement pour avoir une ref

2020-04-24 13:16 UTC, ebaudet approved these changes
Nickel !

2020-04-24 15:18 UTC, merged