Bug/various issues
tnicolas42/bomberman pull request #204
Opened 2020-05-12 18:39 UTC by ebaudet

# PR various fix

- fix #198 : Calculation of killed enemies in score
- fix #195 : The bonus are destroyed in a concatenated explosion
- fix #197 : wake crispy enemy when player is at a radius of 2 blocks
- fix #199 : The APP doesn't contain the lib, and does not work if they are not installed.
- fix #203 : Change configs and saves folder for macos.
- fix shader \ return line

2020-05-13 09:01 UTC, timnicolas approved these changes
ca compile pas sur travis mais sinon OK

2020-05-13 10:42 UTC, zer0nim reviewed
Ça compile pas sur Linux je check ça

2020-05-13 11:25 UTC, zer0nim approved these changes

2020-05-13 11:44 UTC, tnicolas42 commented on includes/bomberman.hpp
>  #ifdef __APPLE__
on pourrais pas faire un truc dans ce genre la ?
```suggestion
#ifdef __APPLE__ || __LINUX__
```

2020-05-13 15:16 UTC, timnicolas requested changes
j'ai un ami qui a test le .dmg et il manque le fichier `libIrrXML.dylib`
```
dyld: Library not loaded: @executable_path/Frameworks/libIrrXML.dylib
  Referenced from: /Applications/bomberman.app/Contents/./Frameworks/libassimp.5.dylib
  Reason: image not found
```

2020-05-13 18:10 UTC, ebaudet reviewed
> j'ai un ami qui a test le .dmg et il manque le fichier `libIrrXML.dylib`
> 
> ```
> dyld: Library not loaded: @executable_path/Frameworks/libIrrXML.dylib
>   Referenced from: /Applications/bomberman.app/Contents/./Frameworks/libassimp.5.dylib
>   Reason: image not found
> ```
@tnicolas42 
Ça doit être parce que tu n'a pas `libIrrXML.dylib` au même endroit que moi, mais je ne sais pas du coup comment trouver son path.
dans `createApp.sh` je l'ai copié comme ça `cp ~/.brew/lib/libIrrXML.dylib $CONT/Frameworks` pcq il est linké comme ça `@rpath/libIrrXML.dylib` et j'ai pas trouvé pour résoudre le path. (dépendance de `libassimp.dylib`)

2020-05-13 18:10 UTC, ebaudet commented on includes/bomberman.hpp
>  #ifdef __APPLE__
nope, pour linux, on veux pas le homedir. 
```
#ifdef __APPLE__
	#define CONFIG_DIR				"/Library/Application Support/bomberman/configs/"
#elif
	#define CONFIG_DIR				"configs/"
#endif
```
`homeDir` est ajouté avant CONFIG_DIR, et du coup pour mac, on le mets dans `~/Library/Application Support/bomberman/configs/` et pour linux, on le laisse là où il était

2020-05-13 19:15 UTC, tnicolas42 commented
pour moi c'est dans `/usr/local`
pour faire un truc generique, tu peut utiliser un truc genre `$(brew --prefix)/lib/fichier.dydl`

2020-05-14 08:26 UTC, tnicolas42 commented
maintenant ca fait ca comme erreur
```
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_respondsToSelector
  Referenced from: /Applications/bomberman.app/Contents/./Frameworks/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_respondsToSelector
  Referenced from: /Applications/bomberman.app/Contents/./Frameworks/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
```
genre j'ai build sous macos 10.15 et ca peut pas etre utilisé en 10.14

2020-05-14 08:29 UTC, tnicolas42 commented
mais sinon ca marche (il faut juste plusieurs .dmg du coup)

2020-05-14 08:29 UTC, timnicolas approved these changes

2020-05-14 12:47 UTC, merged