Feature/settings menu
tnicolas42/bomberman pull request #48
Opened 2020-03-12 16:35 UTC by guilhemSmith

close #9

2020-03-12 16:51 UTC, timnicolas approved these changes
faut qu'on fasse gaffe, il y a pas mal de code qu'on as tout les 2 fait, je met un comment "duplicate" dessus et je vais resourdre de mon coté (#46)

2020-03-12 16:51 UTC, tnicolas42 commented on includes/utils/opengl/Inputs.hpp
> +	std::string								_getInputKeyName(InputType::Enum type);
duplicate

2020-03-12 16:51 UTC, tnicolas42 commented on includes/utils/opengl/UI/ABaseUI.hpp
> +		void			draw();
duplicate

2020-03-12 16:51 UTC, tnicolas42 commented on includes/utils/opengl/UI/ABaseUI.hpp
> +		ABaseUI &	setEnabled(bool enable);
duplicate

2020-03-12 16:51 UTC, tnicolas42 commented on includes/utils/opengl/Inputs.hpp
> +	static std::string						getInputKeyName(InputType::Enum type);
duplicate

2020-03-12 16:51 UTC, tnicolas42 commented on includes/utils/opengl/UI/ABaseUI.hpp
> +		bool		_enabled;
duplicate

2020-03-12 16:51 UTC, tnicolas42 commented on srcs/gui/Gui.cpp
> +	if (Inputs::shouldQuit() || Inputs::getKey(InputType::Enum::CANCEL)) {
duplicate
j'ai changé un peu le fonctionnement ici en creant 2 fonctions
```
preUpdate()  // called before others update
postUpdate()  // called after others update
```

2020-03-12 16:51 UTC, tnicolas42 commented on srcs/utils/opengl/Inputs.cpp
> +}
duplicate

2020-03-12 17:47 UTC, timnicolas requested changes
en testant, j'ai trouvé un bug.

Il faut empecher l'ecran de se mettre a plus que la resolution max de l'ordi (je sais pas si c'est faisable). Mais en gros ca bloque complement (on peut plus appuyer sur les boutons apres)

2020-03-12 18:06 UTC, zer0nim approved these changes

2020-03-12 18:24 UTC, ebaudet approved these changes

2020-03-13 09:15 UTC, timnicolas approved these changes
en vrai tu peut merge, le bug de resolution max d'ecran on pourra le resoudre quand on va fix le bug de taille de boutons

2020-03-13 11:11 UTC, merged